spring:
    cloud:
        function:
            definition: brevErBestiltFunction
        stream:
            bindings:
                brevErBestiltFunction-in-0:
                    destination: pensjonsbrev.brev-er-bestilt
                    group: pensjonsbrev
                brevErBestiltFunction-out-0:
                    destination: pensjonsbrev.brev-data-grunnlag

---
spring:
    profiles: gcp
    cloud:
        stream:
            kafka:
                binder:
                    brokers: ${KAFKA_BROKERS}
                    configuration:
                        security:
                            protocol: SSL
                        ssl:
                            truststore:
                                location: ${KAFKA_TRUSTSTORE_PATH}
                                password: ${KAFKA_CREDSTORE_PASSWORD}
                            keystore:
                                location: ${KAFKA_KEYSTORE_PATH}
                                password: ${KAFKA_CREDSTORE_PASSWORD}
                                type: PKCS12
                            key:
                                password: ${KAFKA_CREDSTORE_PASSWORD}
