spring:
    cloud:
        function:
            definition: brevErBestiltFunction
        stream:
            bindings:
                brevErBestiltFunction-in-0:
                    destination: pensjonsbrev.brev-er-bestilt
                    group: pensjonsbrev
                brevErBestiltFunction-out-0:
                    destination: pensjonsbrev.brev-data-grunnlag
