security-token-service:
    client:
        url: https://api-gw-q1.oera.no/security-token-service/rest/v1/sts
        username: ${USERNAME_SRV_BRUKER}
        password: ${PASSWORD_SRV_BRUKER}
        apikey: ${STS_API_KEY}

pdl-api:
    client:
        url: https://api-gw-q1.oera.no/pdl-api/graphql
        apikey: ${PDL_API_KEY}
vedtak-api:
    client:
        url: https://api-gw-q1.oera.no/pensjon-fss/pensjon-ws/api/vedtak/vedtak/
        apikey: ${VEDTAK_API_KEY}
sak-api:
    client:
        url: https://api-gw-q1.oera.no/pensjon-fss/pensjon-ws/api/sak/sakid/
        apikey: ${SAK_API_KEY}

spring.cloud:
    function.definition: brevErBestilt;brevErBestiltDlt
    stream:
        bindings:
            brevErBestilt-in-0:
                destination: pensjonsbrev.brev-er-bestilt
                group: pensjonsbrev
                maxAttempts: 3
                backOffInitialInterval: 2000
                backOffMaxInterval: 20000
                backOffMultiplier: 2
            brevErBestilt-out-0.destination: pensjonsbrev.brev-data-grunnlag
            brevErBestiltDlt-in-0:
                destination: pensjonsbrev.brev-er-bestilt-dlt
                group: prepare-brevdata-grunnlag
                maxAttempts: 1
            brevErBestiltDlt-out-0.destination: pensjonsbrev.brev-data-grunnlag
        kafka.default.consumer:
            enableDlq: true
            dlqName: pensjonsbrev.brev-er-bestilt-dlt

management.endpoints.web.exposure.include: bindings


---
spring:
    profiles: vdi

security-token-service:
    client:
        url: https://security-token-service.dev.adeo.no/security-token-service/rest/v1/sts