spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: ${KAFKA_BROKERS}
                    configuration:
                        security:
                            protocol: SSL
                        ssl:
                            truststore:
                                location: ${KAFKA_TRUSTSTORE_PATH}
                                password: ${KAFKA_CREDSTORE_PASSWORD}
                            keystore:
                                location: ${KAFKA_KEYSTORE_PATH}
                                password: ${KAFKA_CREDSTORE_PASSWORD}
                                type: PKCS12
                            key:
                                password: ${KAFKA_CREDSTORE_PASSWORD}
