openapi: 3.0.0
info:
  version: 1.0.0
  title: Brevbestilling API
  description: API that describes brevbestilling

paths:
  /brevbestilling:
    post:
      description: Service for brevbestilling
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'brevbestilling-models.yaml#/components/schemas/brevBestillingRequest'
      responses:
        '200':
          description: Successful response

  /brevErBestillt:
    post:
      description: Service for brev er bestillt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'brevbestilling-models.yaml#/components/schemas/brevErBestilt'
      responses:
        '200':
            description: Successful response
            content:
                application/json:
                    schema:
                      $ref: 'brevbestilling-models.yaml#/components/schemas/brevBestillingResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []