security-token-service:
    client:
        url: https://api-gw-q1.oera.no/security-token-service/rest/v1/sts
        username: ${USERNAME_SRV_BRUKER}
        password: ${PASSWORD_SRV_BRUKER}
        apikey: ${STS_API_KEY}

brevmetadata:
    endpoint:
        url: https://pensjon-brevmetadata.dev.adeo.no/api/brevdata

# Binding properties
spring:
    cloud:
        function:
            definition: bestillBrevFunction #;bestillBrevSupplier
        stream:
            bindings:
                bestillBrevFunction-out-0:
                    destination: BREV_ER_BESTILLT
                bestillBrevFunction-in-0:
                    destination: BREV_BESTILLING
                    group: embeddedKafkaApplication
#               bestillBrevSupplier-out-0:
#                   destination: BREV_ER_BESTILLT

---
spring:
    profiles: vdi

security-token-service:
    client:
        url: https://security-token-service-t4.nais.preprod.local/rest/v1/sts
