server:
    port: 8081

spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: localhost:9092

joark-api:
    client:
        url: PlaceHolder
        apikey: PlaceHolder
