security-token-service:
    client:
        url: https://api-gw-q1.oera.no/security-token-service/rest/v1/sts
        username: ${USERNAME_SRV_BRUKER}
        password: ${PASSWORD_SRV_BRUKER}
        apikey: ${STS_API_KEY}

brevmetadata:
    client:
        url: http://pensjon-brevmetadata/api/brevdata

joark-api:
    client:
        url: https://api-gw-q1.oera.no/dokarkiv/rest/journalpostapi/v1/journalpost
        apikey: ${JOARK_API_KEY}

# Binding properties
spring:
    cloud:
        function:
            definition: brevbestilling
        stream:
            bindings:
                brevbestilling-out-0:
                    destination: pensjonsbrev.brev-er-bestilt

openapi:
    brevbestilling-integrasjon:
        base-path: /api
---
spring:
    profiles: vdi

security-token-service:
    client:
        url: https://security-token-service-t4.nais.preprod.local/rest/v1/sts
