security-token-service:
    client:
        url: https://api-gw-q1.oera.no/security-token-service/rest/v1/sts
        username: ${USERNAME_SRV_BRUKER}
        password: ${PASSWORD_SRV_BRUKER}
        apikey: ${STS_API_KEY}

brevmetadata:
    client:
        url: http://pensjon-brevmetadata/api/brevdata

# Binding properties
spring:
    cloud:
        function:
            definition: bestillBrevSupplier
        stream:
            bindings:
                bestillBrevSupplier-out-0:
                    destination: pensjonsbrev.brev-er-bestilt
            poller:
                fixed-delay: 10000

---
spring:
    profiles: vdi

security-token-service:
    client:
        url: https://security-token-service-t4.nais.preprod.local/rest/v1/sts
