apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: prepare-brevdata-grunnlag
  namespace: pensjonsbrev
  labels:
    team: pensjonsbrev
spec:
  image: {{image}}
  kafka:
    pool: nav-dev
  envFrom:
    - secret: srvbrukker-brev-bestilling
    - secret: apikey-prepare-brevdata-grunnlag
  accessPolicy:
    outbound:
      rules:
        - application: pdl-api
      external:
        - host: api-gw-q1.oera.no