apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-brev-bestilling
  namespace: pensjonsbrev
  labels:
    team: pensjonsbrev
spec:
  image: {{image}}
  kafka:
    pool: nav-dev
  envFrom:
    - secret: apikey-pensjon-brev-bestilling
    - secret: srvbrukker-brev-bestilling
    - secret: apikey-prepare-brevdata-grunnlag
  ingresses:
    - "https://pensjon-brev-bestilling.dev.adeo.no/"
  accessPolicy:
    outbound:
      external: 
        - host: api-gw-q1.oera.no