apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: prepare-brevdata-grunnlag
  namespace: pensjonsbrev
  labels:
    team: pensjonsbrev
spec:
  image: {{image}}
  accessPolicy: 
    external:
        - host: api-gw-t4.adeo.no