name: Build, push, and deploy pensjon-brev-bestilling

on:
  push:
    paths:
      - 'brev-bestilling-boot/**'
      - 'nais/nais-brev-bestilling.yml'
  workflow_run:
    workflows:
      - DeploySTSClient
      - BrevbestillingIntegrasjon
    types:
      - completed

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/pensjon-brev-bestilling:${{ github.sha }}

defaults:
  run:
    working-directory: brev-bestilling-boot

jobs:
  build-brev-bestilling:
    name: Build and push brev-bestilling Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --settings ../.github/settings.xml package --file pom.xml
      - name: Build and publish brev-bestilling Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} . --file Dockerfile
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}

  deploy-brev-bestilling:
    name: Deploy build-brev-bestilling to NAIS
    needs: build-brev-bestilling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais-brev-bestilling.yml,topics/pensjon-brev-bestilling.yaml