name: BrevbestillingIntegrasjon

on:
  push:
    paths:
      - 'brevbestilling-integrasjon/**'

defaults:
  run:
    working-directory: brevbestilling-integrasjon

jobs:
  deploy-brevbestilling-integrasjon:
    name: Deploy brevbestilling-integrasjon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --settings ../.github/settings.xml deploy --file pom.xml