name: Build, push, and deploy

on: [push]

env:
  IMAGE_BREV_BESTILLING: docker.pkg.github.com/${{ github.repository }}/pensjon-brev-bestilling:${{ github.sha }}
  IMAGE_PREPARE_BREVDATA_GRUNNLAG: docker.pkg.github.com/${{ github.repository }}/prepare-brevdata-grunnlag:${{ github.sha }}
  IMAGE_PREPARE_BREV: docker.pkg.github.com/${{ github.repository }}/prepare-brev:${{ github.sha }}

jobs:
  

  build-brev-bestilling:
    name: Build and push brev-bestilling Docker container
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v1
      with:
          java-version: '11.x'
    - name: Build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B package --file pom.xml
    - name: Build and publish brev-bestilling Docker image
      env:
        IMAGE: ${{env.IMAGE_BREV_BESTILLING}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker build --tag ${IMAGE} . --file Dockerfile-brev-bestilling
        docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
        docker push ${IMAGE}

  
  build-prepare-brevdata-grunnlag:
    name: Build and push prepare-brevdata-grunnlag Docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v1
      with:
          java-version: '11.x'
    - name: Build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B package --file pom.xml
    - name: Build and publish prepare-brevdata-grunnlag Docker image
      env:
        IMAGE: ${{env.IMAGE_PREPARE_BREVDATA_GRUNNLAG}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker build --file Dockerfile-prepare-brevdata-grunnlag --tag ${IMAGE} .
        docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
        docker push ${IMAGE}

  build-prepare-brev:
    name: Build and push prepare-brev Docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v1
      with:
          java-version: '11.x'
    - name: Build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B package --file pom.xml
    - name: Build and publish prepare-brev Docker image
      env:
        IMAGE: ${{env.IMAGE_PREPARE_BREV}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        docker build --file Dockerfile-prepare-brev --tag ${IMAGE} .
        docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
        docker push ${IMAGE}

  deploy-brev-bestilling:
    name: Deploy build-brev-bestilling to NAIS
    needs: build-brev-bestilling
    #if: github.ref == 'refs/heads/master' touch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1  
      env:
        IMAGE: ${{env.IMAGE_BREV_BESTILLING}}
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: nais/nais-brev-bestilling.yml,topics/pensjon-brev-bestilling.yaml
   
  deploy-prepare-brevdata-grunnlag:
    name: Deploy build-prepare-brevdata-grunnlag to NAIS
    needs: build-prepare-brevdata-grunnlag
    #if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1  
      env:
        IMAGE: ${{env.IMAGE_PREPARE_BREVDATA_GRUNNLAG}}
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: nais/nais-prepare-brevdata-grunnlag.yml
        
  deploy-prepare-brev:
    name: Deploy build-prepare-brev to NAIS
    needs: build-prepare-brev
    #if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nais/deploy/actions/deploy@v1  
      env:
        IMAGE: ${{env.IMAGE_PREPARE_BREV}}
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: nais/nais-prepare-brev.yml,topics/pensjon-data-grunnlag.yaml
