name: ParentPOM

on:
  push:
    paths:
      - 'pom.xml'

jobs:
  deploy-parent-pom:
    name: Deploy parent-pom
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B -N --settings .github/settings.xml deploy