name: PensjonIntegrasjon

on:
  push:
    paths:
      - 'pensjon-integrasjon/**'

defaults:
  run:
    working-directory: pensjon-integrasjon

jobs:
  deploy-pensjon-integrasjon:
    name: Deploy pensjon-integrasjon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --settings ../.github/settings.xml test --file pom.xml