name: Build, push, and deploy prepare-brevdata-grunnlag

on:
  push:
    paths:
      - 'prepare-brevdata-grunnlag/**'
  workflow_run:
    workflows:
      - DeploySTSClient
      - DeployCommonLib
      - PensjonIntegrasjon
    types:
      - completed

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/prepare-brevdata-grunnlag:${{ github.sha }}

defaults:
  run:
    working-directory: prepare-brevdata-grunnlag

jobs:
  build-prepare-brevdata-grunnlag:
    name: Build and push prepare-brevdata-grunnlag Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --settings ../.github/settings.xml package --file pom.xml
      - name: Build and publish prepare-brevdata-grunnlag Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} . --file Dockerfile
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}

  deploy-prepare-brevdata-grunnlag:
    name: Deploy prepare-brevdata-grunnlag to NAIS
    needs: build-prepare-brevdata-grunnlag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais-prepare-brevdata-grunnlag.yml,topics/pensjon-brev-bestilling-dlt.yaml