name: DeploySTSClient

on:
  push:
    paths:
      - 'sts-client/**'
  workflow_run:
    workflows:
      - ParentPOM
    types:
      - completed


defaults:
  run:
    working-directory: sts-client

jobs:
  deploy-sts-client:
    name: Deploy sts-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B --settings ../.github/settings.xml deploy --file pom.xml